input_dir: '/home/laurits/230607_newRun'
plotting_algorithms:
  HPS: ''
  HPS_DeepTau: '/home/laurits/230701_Deeptau_fl2'
  LorentzNet: ''
  ParticleTransformer: '/home/laurits/230630_ParticleTransformer_final'
  FastCMSTau: '/home/laurits/230607_FastCMS'
  # MLReco_DeepTau: ''
  # TwoStep_GNN
  # SimpleDNN: ''
plotting_metrics:
  ROC: True
  fakerate: True
  efficiency: True
  tauClassifier: True
  energy_resolution: False
  decaymode: True
  HPS_comparison: True
HPS_comparison:
  HPS_with_quality_cuts: '/home/laurits/230612_HPS_cuts/'
  HPS: '/home/laurits/230607_newRun'
defaults:
  - metrics
  - _self_