plotting:
  output_dir: /home/laurits/CLIC_metrics_xyz
  n_files: -1
algorithms:
  EndToEnd:
    sig_ntuples_dir: /foo/bar
    bkg_ntuples_dir: /foo/bar
    compare: False
  HPS_DeepTau:
    sig_ntuples_dir: /foo/bar
    bkg_ntuples_dir: /foo/bar
    compare: False
  MLReco_DeepTau:
    sig_ntuples_dir: /foo/bar
    bkg_ntuples_dir: /foo/bar
    compare: False
  HPS_only:
    sig_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/HPS/ZH_Htautau
    bkg_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/HPS/QCD
    compare: False
  Oracle:
    sig_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/Oracle/ZH_Htautau
    bkg_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/Oracle/QCD
    compare: True
  FastCMSTau:
    sig_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/FastCMSTau/ZH_Htautau
    bkg_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/FastCMSTau/QCD
    compare: True
  SimpleDNN:
    sig_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/SimpleDNN/ZH_Htautau
    bkg_ntuples_dir: /local/$USER/CLIC_taus_20230215_v1/SimpleDNN/QCD
    compare: False
metrics:
  denominator: "pt >= 20 && |eta| < 2.3"
  numerator: "pt >= 20 && |eta| < 2.3"
  efficiency:
    variables:
      - name: pt
        x_range: [20, 500]
        n_bins: 32
      - name: eta
        x_range: [-2.6, 2.6]
        n_bins: 32
      - name: theta
        x_range: [-3.14, 3.14]
        n_bins: 32
  # fake_ref: reco_jet
  # eff_obj: gen_jet/tau
