tauClassifierCut: 0.5
plotting:
  output_dir: /home/laurits/CLIC_metrics_20220223
  n_files: -1
algorithms:
  LorentzNet:
    sig_ntuples_dir: /scratch-persistent/veelken/CLIC_tau_ntuples/2023Mar02/LorentzNet/ZH_Htautau
    bkg_ntuples_dir: /scratch-persistent/veelken/CLIC_tau_ntuples/2023Mar02/LorentzNet/QCD
    compare: True
  HPS_DeepTau:
    sig_ntuples_dir: /foo/bar
    bkg_ntuples_dir: /foo/bar
    compare: False
  ParticleTransformer:
    sig_ntuples_dir: /scratch-persistent/veelken/CLIC_tau_ntuples/2023Mar03/ParticleTransformer/ZH_Htautau
    bkg_ntuples_dir: /scratch-persistent/veelken/CLIC_tau_ntuples/2023Mar03/ParticleTransformer/QCD
    compare: True
  MLReco_DeepTau:
    sig_ntuples_dir: /foo/bar
    bkg_ntuples_dir: /foo/bar
    compare: False
  HPS:
    sig_ntuples_dir: /local/laurits/CLIC_taus_20230215_v1/HPS/ZH_Htautau
    bkg_ntuples_dir: /local/laurits/CLIC_taus_20230215_v1/HPS/QCD
    compare: False
  HPS_wo_quality_cuts:
    sig_ntuples_dir: /scratch-persistent/veelken/CLIC_tau_ntuples/2023Mar01_woPtCuts/HPS/ZH_Htautau
    bkg_ntuples_dir: /scratch-persistent/veelken/CLIC_tau_ntuples/2023Mar01_woPtCuts/HPS/QCD
    compare: True
  Oracle:
    sig_ntuples_dir: /local/laurits/CLIC_taus_20230215_v1/Oracle/ZH_Htautau
    bkg_ntuples_dir: /local/laurits/CLIC_taus_20230215_v1/Oracle/QCD
    compare: False
  FastCMSTau:
    sig_ntuples_dir: /local/tolange/CLIC_FastCMSTau/FastCMSTau/ZH_Htautau
    bkg_ntuples_dir: /local/tolange/CLIC_FastCMSTau/FastCMSTau/QCD
    compare: True
  SimpleDNN:
    sig_ntuples_dir: /scratch-persistent/joosep/ml-tau-reco/CLIC_data/2023_02_22/SimpleDNN/ZH_Htautau/
    bkg_ntuples_dir: /scratch-persistent/joosep/ml-tau-reco/CLIC_data/2023_02_22/SimpleDNN/QCD/
    compare: True
metrics:
  denominator: "pt >= 20 && |eta| < 2.3"
  numerator: "pt >= 20 && |eta| < 2.3"
  WPs:
    HPS_wo_quality_cuts:
      Loose: -1
      Medium: 0.951
      Tight: 0.467
    LorentzNet:
      Loose: 0.972
      Medium: 0.946
      Tight: 0.878
  efficiency:
    variables:
      - name: pt
        x_range: [20, 500]
        n_bins: 32
      - name: eta
        x_range: [-2.6, 2.6]
        n_bins: 32
      - name: theta
        x_range: [-3.14, 3.14]
        n_bins: 32
  # fake_ref: reco_jet
  # eff_obj: gen_jet/tau
defaults:
  - datasets: datasets
  - _self_
