use_multiprocessing: True
tree_path: events
branches:
  - MCParticles
  - MergedRecoParticles
  - SiTracks_Refitted_1
  - PrimaryVertices
test_run: False
samples_to_process:
  - ZH_Htautau
  - QCD
samples:
  ZH_Htautau:
    input_dir: /local/joosep/clic_edm4hep_2023_02_27/p8_ee_ZH_Htautau_ecm380/
    output_dir: /scratch-persistent/laurits/CLIC_data_20230302/ZH_Htautau
  QCD:
    input_dir: /local/joosep/clic_edm4hep_2023_02_27/p8_ee_qq_ecm380/
    output_dir: /scratch-persistent/laurits/CLIC_data_20230302/QCD
  TT:
    input_dir: /local/joosep/clic_edm4hep_2023_02_27/p8_ee_tt_ecm365
    output_dir: /scratch-persistent/laurits/CLIC_data_20230302/TT
validation:
  output_dir: $HOME/CLIC_ntuple_validation
  validation_samples:
    - ZH_Htautau
    - QCD
