tree_path: events
branches:
  - MCParticles
  - MergedRecoParticles
test_run: False
samples_to_process:
  - ZH_Htautau
  - QCD
samples:
  ZH_Htautau:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_ZH_Htautau_ecm380/
    output_dir: /scratch-persistent/laurits/CLIC_data_2023021X/ZH_Htautau
  QCD:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_qcd_ecm365
    output_dir: /scratch-persistent/laurits/CLIC_data_2023021X/QCD
  TT:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_tt_ecm365
    output_dir: /scratch-persistent/laurits/CLIC_data_[DATE]/TT
  ZZ_fullhad:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_ZZ_fullhad_ecm365
    output_dir: /scratch-persistent/laurits/CLIC_data_[DATE]/ZZ_fullhad
  Z_Ztautau:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_Z_Ztautau_ecm125
    output_dir: /scratch-persistent/laurits/CLIC_data_[DATE]/Z_Ztautau
validation:
  output_dir: $HOME/CLIC_ntuple_validation
  validation_samples:
    - ZH_Htautau
    - QCD
