tree_path: events
branches:
  - MCParticles
  - MergedRecoParticles
test_run: False
input_dir: /local/joosep/clic_edm4hep/p8_ee_qcd_ecm365
output_dir: /local/laurits/CLIC_data/QCD
samples_to_process:
  - ZH_Htautau
  - QCD
samples:
  ZH_Htautau:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_ZH_Htautau_ecm380/
    output_dir: /local/laurits/CLIC_data/ZH_Htautau_
  QCD:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_qcd_ecm365
    output_dir: /local/laurits/CLIC_data/QCD_
  TT:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_tt_ecm365
    output_dir: /local/laurits/CLIC_data/TT
  ZZ_fullhad:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_ZZ_fullhad_ecm365
    output_dir: /local/laurits/CLIC_data/ZZ_fullhad
  Z_Ztautau:
    input_dir: /local/joosep/clic_edm4hep/p8_ee_Z_Ztautau_ecm125
    output_dir: /local/laurits/CLIC_data/Z_Ztautau
validation:
  output_dir: $HOME/CLIC_ntuple_validation
  validation_samples:
    - ZH_Htautau
